services:
  - type: web
    name: portfolio-chatbot
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: GOOGLE_API_KEY_1
        sync: false

      - key: GOOGLE_API_KEY_2
        sync: false

      - key: GOOGLE_API_KEY_3
        sync: false

      - key: GOOGLE_API_KEY_4
        sync: false

      - key: GEMINI_MODEL
        value: gemini-2.5-flash

      # Pinecone / RAG
      - key: PINECONE_API_KEY
        sync: false

      - key: PINECONE_INDEX_NAME
        value: voice-agent

      - key: PINECONE_CLOUD
        value: aws

      - key: PINECONE_REGION
        value: us-east-1

      - key: EMBEDDING_MODEL_NAME
        value: llama-text-embed-v2

      - key: EMBEDDING_DIMENSION
        value: 384

      - key: RAG_TOP_K
        value: 3

      # Memory
      - key: MEMORY_BACKEND
        value: dict

      - key: APP_ENV
        value: production

      - key: DEBUG
        value: false

      - key: CORS_ORIGINS
        value: '["https://vishalsahilai.vercel.app"]'